version: '3'
services:
  frontend:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GEMINI_API_TOKEN=${GEMINI_API_TOKEN}
